# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    #  Base Image
    config.vm.box = "bento/ubuntu-20.04"
    # Shared Directory Settings
    config.vm.synced_folder "~/shared/", "/home/vagrant/shared"

    # Setting Virtual Box
    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.cpus = 2
        vb.memory = "4096"
        vb.customize [
            "modifyvm"          , :id,
            "--vram"            , "256",
            "--clipboard"       , "bidirectional",
            "--accelerate3d"    , "on",
            "--hwvirtex"        , "on",
            "--nestedpaging"    , "on",
            "--largepages"      , "on",
            "--ioapic"          , "on",
            "--pae"             , "on",
            "--paravirtprovider", "kvm",
        ]
    end

    # Initial launch script
    config.vm.provision :shell, :inline => <<-EOL
        # Desktop Environment
        sudo apt install -y ubuntu-desktop gnome-tweak-tool
        # Change the time zone to Japan time
        sudo timedatectl set-timezone Asia/Tokyo
    EOL

end
